// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  module2Sidebar: [
    {
      type: 'doc',
      id: 'module-2/index', // This would be the main module page
      label: 'Module 2: The Digital Twin (Simulation Environment)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Simulation Environments',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-1/chapter1',
          label: 'Overview of Simulation Platforms',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-1/lab-exercise',
          label: 'Lab: Setting up Isaac Sim and Gazebo',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Physics Simulation Concepts',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-2/chapter2',
          label: 'Physics Parameters and Simulation',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-2/lab-exercise',
          label: 'Lab: Configuring Physics Parameters',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensor Simulation',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-3/chapter3',
          label: 'Sensor Types and Configurations',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-3/lab-exercise',
          label: 'Lab: Setting up Virtual Sensors',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Visualization for Human-Robot Interaction',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-4/chapter4',
          label: 'Visualization Techniques',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-4/lab-exercise',
          label: 'Lab: Robot State Visualization',
        },
      ],
    },
  ],
  module3Sidebar: [
    {
      type: 'doc',
      id: 'module-3/index', // This would be the main module page
      label: 'Module 3: The AI-Robot Brain (Perception & Navigation)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Advanced Simulation Scenarios',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-1/chapter1',
          label: 'Complex Simulation Environments',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-1/lab-exercise',
          label: 'Lab: Creating Complex Simulation Scenes',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: AI Perception for Robotics',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-2/chapter2',
          label: 'Perception Pipeline Components',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-2/lab-exercise',
          label: 'Lab: Object Detection and SLAM',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Navigation Systems and Path Planning',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-3/chapter3',
          label: 'Navigation with Nav2',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-3/lab-exercise',
          label: 'Lab: Configuring Nav2 and Path Planning',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Sim-to-Real Transfer Concepts',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-4/chapter4',
          label: 'Bridging Simulation and Reality',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-4/lab-exercise',
          label: 'Lab: Sim-to-Real Validation',
        },
      ],
    },
  ],
  module4Sidebar: [
    {
      type: 'doc',
      id: 'module-4/index', // This would be the main module page
      label: 'Module 4: Vision-Language-Action (VLA)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Speech Processing for Robotics',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-1/chapter1',
          label: 'Speech-to-Text Conversion',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-1/lab-exercise',
          label: 'Lab: Implementing Speech-to-Text Conversion',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: LLM-Based Task Planning',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-2/chapter2',
          label: 'Large Language Models for Planning',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-2/lab-exercise',
          label: 'Lab: Creating LLM-driven Planning Pipeline',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Vision-Action Integration',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-3/chapter3',
          label: 'Linking Vision and Action',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-3/lab-exercise',
          label: 'Lab: Integrating Vision Feedback into Action Loops',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Safety and Action Validation',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-4/chapter4',
          label: 'Validation and Safety Mechanisms',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-4/lab-exercise',
          label: 'Lab: Implementing Safety Validation Layers',
        },
      ],
    },
  ],
};

module.exports = sidebars;