import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Getting Started with Physical-AI & Humanoid Robotics',
    },
    {type: 'autogenerated', dirName: '.'}
  ],

  module1Sidebar: [
    {
      type: 'doc',
      id: 'module-1/index',
      label: 'Module 1: ROS 2 Fundamentals',
    },
    {
      type: 'category',
      label: 'Chapter 1: ROS 2 Communication',
      items: [
        'module-1/chapter-1-ros2-communication',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: rclpy Integration',
      items: [
        'module-1/chapter-2-rclpy-integration',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: URDF Fundamentals',
      items: [
        'module-1/chapter-3-urdf-fundamentals',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: AI-Robot Bridge',
      items: [
        'module-1/chapter-4-ai-robot-bridge',
      ],
    },
    {
      type: 'category',
      label: 'Lab Exercises',
      items: [
        'module-1/lab-exercise-1-nodes-topics-services',
        'module-1/lab-exercise-2-ai-agent-connection',
        'module-1/lab-exercise-3-urdf-humanoid-limb',
        'module-1/lab-exercise-4-ai-humanoid-task',
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        'module-1/module-summary',
        'module-1/citation-system',
        'module-1/urdf-validation-examples',
      ],
    },
  ],

  module2Sidebar: [
    {
      type: 'doc',
      id: 'module-2/index',
      label: 'Module 2: The Digital Twin (Simulation Environment)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Simulation Environments',
      items: [
        'module-2/chapter-1/chapter1',
        'module-2/chapter-1/isaac-sim-lab',
        'module-2/chapter-1/gazebo-lab',
        'module-2/chapter-1/comprehension-checks',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Physics Simulation Concepts',
      items: [
        'module-2/chapter-2/chapter2',
        'module-2/chapter-2/comprehension-checks',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensor Simulation',
      items: [
        'module-2/chapter-3/chapter3',
        'module-2/chapter-3/comprehension-checks',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Visualization for Human-Robot Interaction',
      items: [
        'module-2/chapter-4/chapter4',
        'module-2/chapter-4/comprehension-checks',
      ],
    },
  ],

  module3Sidebar: [
    {
      type: 'doc',
      id: 'module-3/index',
      label: 'Module 3: The AI-Robot Brain (Perception & Navigation)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Advanced Simulation Scenarios',
      items: [
        'module-3/chapter-1/chapter1',
        'module-3/chapter-1/gazebo-lab',
        'module-3/chapter-1/comprehension-checks',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: AI Perception for Robotics',
      items: [
        'module-3/chapter-2/chapter2',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Navigation Systems and Path Planning',
      items: [
        'module-3/chapter-3/chapter3',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Sim-to-Real Transfer Concepts',
      items: [
        'module-3/chapter-4/chapter4',
      ],
    },
  ],

  module4Sidebar: [
    {
      type: 'doc',
      id: 'module-4/index',
      label: 'Module 4: Vision-Language-Action (VLA)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Speech Processing for Robotics',
      items: [
        'module-4/chapter-1/index',
        'module-4/chapter-1/lab-exercise',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: LLM-Based Task Planning',
      items: [
        'module-4/chapter-2/index',
        'module-4/chapter-2/lab-exercise',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Vision-Action Integration',
      items: [
        'module-4/chapter-3/index',
        'module-4/chapter-3/lab-exercise',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Safety and Action Validation',
      items: [
        'module-4/chapter-4/index',
        'module-4/chapter-4/lab-exercise',
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        'module-4/comprehension-checks',
        'module-4/citations',
        'module-4/vla-pipeline-diagram',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
