// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  module1Sidebar: [
    {
      type: 'doc',
      id: 'module-1/index',
      label: 'Module 1: ROS 2 Fundamentals',
    },
    {
      type: 'category',
      label: 'Chapter 1: ROS 2 Communication',
      items: [
        {
          type: 'doc',
          id: 'module-1/chapter-1-ros2-communication',
          label: 'ROS 2 Communication Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: rclpy Integration',
      items: [
        {
          type: 'doc',
          id: 'module-1/chapter-2-rclpy-integration',
          label: 'Python Integration with rclpy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: URDF Fundamentals',
      items: [
        {
          type: 'doc',
          id: 'module-1/chapter-3-urdf-fundamentals',
          label: 'Unified Robot Description Format',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: AI-Robot Bridge',
      items: [
        {
          type: 'doc',
          id: 'module-1/chapter-4-ai-robot-bridge',
          label: 'Connecting AI Systems to Robots',
        },
      ],
    },
    {
      type: 'category',
      label: 'Lab Exercises',
      items: [
        {
          type: 'doc',
          id: 'module-1/lab-exercise-1-nodes-topics-services',
          label: 'Lab Exercise 1: Nodes, Topics, Services',
        },
        {
          type: 'doc',
          id: 'module-1/lab-exercise-2-ai-agent-connection',
          label: 'Lab Exercise 2: AI Agent Connection',
        },
        {
          type: 'doc',
          id: 'module-1/lab-exercise-3-urdf-humanoid-limb',
          label: 'Lab Exercise 3: URDF Humanoid Limb',
        },
        {
          type: 'doc',
          id: 'module-1/lab-exercise-4-ai-humanoid-task',
          label: 'Lab Exercise 4: AI Humanoid Task',
        },
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        {
          type: 'doc',
          id: 'module-1/module-summary',
          label: 'Module Summary',
        },
        {
          type: 'doc',
          id: 'module-1/citation-system',
          label: 'Citation System',
        },
        {
          type: 'doc',
          id: 'module-1/urdf-validation-examples',
          label: 'URDF Validation Examples',
        },
      ],
    },
  ],
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  module2Sidebar: [
    {
      type: 'doc',
      id: 'module-2/index',
      label: 'Module 2: The Digital Twin (Simulation Environment)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Simulation Environments',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-1/chapter1',
          label: 'Overview of Simulation Platforms',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-1/isaac-sim-lab',
          label: 'Lab: Isaac Sim Setup',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-1/gazebo-lab',
          label: 'Lab: Gazebo Setup',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-1/comprehension-checks',
          label: 'Comprehension Checks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Physics Simulation Concepts',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-2/chapter2',
          label: 'Physics Parameters and Simulation',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-2/comprehension-checks',
          label: 'Comprehension Checks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensor Simulation',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-3/chapter3',
          label: 'Sensor Types and Configurations',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-3/comprehension-checks',
          label: 'Comprehension Checks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Visualization for Human-Robot Interaction',
      items: [
        {
          type: 'doc',
          id: 'module-2/chapter-4/chapter4',
          label: 'Visualization Techniques',
        },
        {
          type: 'doc',
          id: 'module-2/chapter-4/comprehension-checks',
          label: 'Comprehension Checks',
        },
      ],
    },
  ],
  module3Sidebar: [
    {
      type: 'doc',
      id: 'module-3/index',
      label: 'Module 3: The AI-Robot Brain (Perception & Navigation)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Advanced Simulation Scenarios',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-1/chapter1',
          label: 'Complex Simulation Environments',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-1/gazebo-lab',
          label: 'Lab: Creating Complex Simulation Scenes',
        },
        {
          type: 'doc',
          id: 'module-3/chapter-1/comprehension-checks',
          label: 'Comprehension Checks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: AI Perception for Robotics',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-2/chapter2',
          label: 'Perception Pipeline Components',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Navigation Systems and Path Planning',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-3/chapter3',
          label: 'Navigation with Nav2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Sim-to-Real Transfer Concepts',
      items: [
        {
          type: 'doc',
          id: 'module-3/chapter-4/chapter4',
          label: 'Bridging Simulation and Reality',
        },
      ],
    },
  ],
  module4Sidebar: [
    {
      type: 'doc',
      id: 'module-4/index', // This would be the main module page
      label: 'Module 4: Vision-Language-Action (VLA)',
    },
    {
      type: 'category',
      label: 'Chapter 1: Speech Processing for Robotics',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-1/index',
          label: 'Speech-to-Text Conversion',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-1/lab-exercise',
          label: 'Lab: Implementing Speech-to-Text Conversion',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: LLM-Based Task Planning',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-2/index',
          label: 'Large Language Models for Planning',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-2/lab-exercise',
          label: 'Lab: Creating LLM-driven Planning Pipeline',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Vision-Action Integration',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-3/index',
          label: 'Linking Vision and Action',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-3/lab-exercise',
          label: 'Lab: Integrating Vision Feedback into Action Loops',
        },
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Safety and Action Validation',
      items: [
        {
          type: 'doc',
          id: 'module-4/chapter-4/index',
          label: 'Validation and Safety Mechanisms',
        },
        {
          type: 'doc',
          id: 'module-4/chapter-4/lab-exercise',
          label: 'Lab: Implementing Safety Validation Layers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        {
          type: 'doc',
          id: 'module-4/comprehension-checks',
          label: 'Comprehension Checks',
        },
        {
          type: 'doc',
          id: 'module-4/citations',
          label: 'Academic Citations',
        },
        {
          type: 'doc',
          id: 'module-4/vla-pipeline-diagram',
          label: 'VLA Pipeline Diagram',
        },
      ],
    },
  ],
};

module.exports = sidebars;